### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Smece12** [corysus/titlovi-com-addon#1]
Hi,
This addon stopped working, any plans on making it work again?

Thank you.

Br.

**Comment by corysus** [comment]
Zdravo, na zalost ovo se desava jer na heroku.com (servis koji se koristi trenutno za hostanje plugin-a) ima limitaciju koja je vjerovatno vec iskoristena. Heroku radi reset ovih limita svakog prvog u mjesecu.

**Comment by Smece12** [comment]
Tnx!!
Any chance on moving the addon to beamup? It's free :)
https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deploying/beamup.md
