### ISSUE TITLE
Mogućnost lokalnog hostanja addona ako niste u mogućnosti opet hostat addon.

### ISSUE THREAD

**Issue by themarin121** [corysus/titlovi-com-addon#7]
Probao sam hostat lokalno addon, ali sam vidio da uzima login token od titlovi-stremio-server.onrender.com koji nije online, jel moguće da stavite i kod od te stranice da se sve može lokalno hostat.

**Comment by corysus** [comment]
Servis je bio ugasen, vjerovatno zbog cestog padanja koliko vidim, postoji neki problem na dijelu servera tj dijela koji preuzima titlove pa cu vidjeti u cemu je problem cim budem mogao. Sada bi vas local addon trebao da radi ali moguce da ce biti problema zbog cestog padanja servisa.
